python predict.py \
  --csv_path /Users/princelu/Desktop/NN/GTZAN/gtzan.csv \
  --audio_root /Users/princelu/Desktop/NN/GTZAN/genres \
  --ckpt_path /Users/princelu/Desktop/NN/GTZAN/checkpoints/checkpoint_best.pt \
  --out_csv /Users/princelu/Desktop/NN/GTZAN/61447070S_submission.csv \
  --hidden_dim 128 \
  --num_layers 2 \
  --dropout 0.1 \
  --timeseries_length 128 \
  --hop_length 512 \
  --target_sr 0