python predict.py \
  --csv_path /Users/princelu/Desktop/NN/GTZAN/gtzan.csv \
  --audio_root /Users/princelu/Desktop/NN/GTZAN/genres \
  --ckpt_path /Users/princelu/Desktop/NN/GTZAN/checkpoints_transformer_trans/checkpoint_best.pt \
  --out_csv /Users/princelu/Desktop/NN/GTZAN/61447070S_submission.csv \
  --num_layers 2 \
  --dropout 0.3 \
  --timeseries_length 256 \
  --hop_length 256 \
  --n_mels 33 \
  --target_sr 22050
